name: Code quality and deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci src

  deploy:
    runs-on: ubuntu-latest
    needs: quality
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10.31.0
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Build project
        run: pnpm build
        env:
          APP_ENV: production
          APP_SESSION_NAME: ${{ secrets.APP_SESSION_NAME }}
          BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
          BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          IMAGE_UPLOADER_API_KEY: ${{ secrets.IMAGE_UPLOADER_API_KEY }}
          IMAGE_UPLOADER_URL: ${{ secrets.IMAGE_UPLOADER_URL }}
          MAILER_API_KEY: ${{ secrets.MAILER_API_KEY }}
          MAILER_REGISTER_URL: ${{ secrets.MAILER_REGISTER_URL }}
          MAILER_BOOKING_URL: ${{ secrets.MAILER_BOOKING_URL }}
          MAILER_CONTACT_URL: ${{ secrets.MAILER_CONTACT_URL }}
          MAILER_FORGOT_PASSWORD_URL: ${{ secrets.MAILER_FORGOT_PASSWORD_URL }}
          PUBLIC_APP_URL: ${{ secrets.PUBLIC_APP_URL }}
          PUBLIC_MIN_PASSWORD_LENGTH: ${{ secrets.PUBLIC_MIN_PASSWORD_LENGTH }}
      - name: Deploy to Netlify
        run: pnpm netlify deploy --prod --message "Deploy from GitHub Actions - Build ${{ github.run_number }}"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 10
